# Generated by Django 5.2.4 on 2025-08-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bath_room',
            field=models.ImageField(blank=True, default='room_images/maxresdefault (2).jpg', upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image',
            field=models.ImageField(blank=True, default='room_images/maxresdefault (2).jpg', upload_to='room_images/'),
        ),
    ]
